In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

diabetes_data = pd.read_csv('../data/train.csv')
#print(diabetes_data['가격'].value_counts())
diabetes_data.head(3)

,ID,생산년도,모델출시년도,브랜드,차량모델명,판매도시,판매구역,주행거리,배기량,압축천연가스(CNG),경유,가솔린,하이브리드,액화석유가스(LPG),가격
0,TRAIN_00000,2018,2014,skoda,fabia,KAT,SLA,85231,999,0,0,1,0,0,51.74
1,TRAIN_00001,2010,2006,toyota,auris,RKO,SWI,135000,1598,0,0,1,0,0,41.47
2,TRAIN_00002,2002,2002,mercedes-benz,clk-klasa,GNI,WIE,255223,1796,0,0,1,0,0,17.81

In [2]:
diabetes_data.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57920 entries, 0 to 57919
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           57920 non-null  object
 1   생산년도         57920 non-null  int64
 2   모델출시년도       57920 non-null  int64
 3   브랜드          57920 non-null  object
 4   차량모델명        57920 non-null  object
 5   판매도시         57920 non-null  object
 6   판매구역         57920 non-null  object
 7   주행거리         57920 non-null  int64
 8   배기량          57920 non-null  int64
 9   압축천연가스(CNG)  57920 non-null  int64
 10  경유           57920 non-null  int64
 11  가솔린          57920 non-null  int64
 12  하이브리드        57920 non-null  int64
 13  액화석유가스(LPG)  57920 non-null  int64
 14  가격           57920 non-null  float64
dtypes: float64(1), int64(9), object(5)
memory usage: 6.6+ MB